param(
    [Parameter(Mandatory = $true)]
    [string]$TaskId,
    [Parameter(Mandatory = $true)]
    [string]$ResultFile,
    [Parameter(Mandatory = $true)]
    [string]$Candidate,
    [string]$WhyItMatters = 'This pattern is worth review for durable memory promotion.',
    [string]$Reviewer = 'pending',
    [bool]$Promote = $false,
    [string]$Notes = 'Generated by offline smoke flow.',
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'AgentBridge.Common.ps1')

$timestamp = Get-Date
$fileName = '{0}-{1}.md' -f $timestamp.ToString('yyyyMMdd-HHmmss'), (ConvertTo-AgentBridgeSlug -Text $TaskId)
$path = Join-Path $Root ("memory-promotions\{0}" -f $fileName)

$content = @(
    '# Memory Promotion Candidate'
    ''
    '## Candidate'
    ''
    '- Preference, pattern, or lesson: {0}' -f $Candidate
    ''
    '## Evidence'
    ''
    '- Task ids: {0}' -f $TaskId
    '- Result files: {0}' -f $ResultFile
    ''
    '## Why it matters'
    ''
    '- {0}' -f $WhyItMatters
    ''
    '## Reviewer Decision'
    ''
    '- Reviewer: {0}' -f $Reviewer
    '- Promote: {0}' -f ($(if ($Promote) { 'yes' } else { 'no' }))
    '- Notes: {0}' -f $Notes
) -join "`n"

Write-AgentBridgeUtf8LfFile -Path $path -Content $content

[pscustomobject]@{
    memory_promotion_path = $path
}
